spring:
  application:
    name: spring-ai-started

  devtools:
    restart:
      enabled: false

  ai:
    openai:
      api-key: ${QIANWEN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen2.5-14b-instruct
